FROM python:3.9

COPY ./requirements.txt /WiseSplit/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /WiseSplit/requirements.txt

COPY ./app /WiseSplit/app/

COPY ./secrets /WiseSplit/app/secrets/

WORKDIR /WiseSplit/app/

CMD ["python","wise_split.py"]
