version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./.env/backend.env
    networks:
      - net
  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    env_file: ./.env/frontend.env
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      driver: default

